# Generated by Django 4.2.4 on 2023-08-31 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("docsplainer", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="user",
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="AIResponse",
        ),
        migrations.DeleteModel(
            name="Document",
        ),
    ]
